name: solium
version: git
summary: A customizable, stand-alone linter for Ethereum Solidity
description: |
  Solium is a linter for Solidity which uses Abstract Syntax Trees and allows
  the user to enable/disable existing rules and add their own ones!

grade: stable
confinement: strict

apps:
  solium:
    command: solium
    plugs: [home, network]

parts:
  solium:
    source: .
    plugin: nodejs
